name: Build Font

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install woff tools
      run: sudo apt-get -y install woff2
    - name: Build Font
      run: ./build.py
    - uses: actions/upload-artifact@v3
      with:
        name: Sieben-7
        path: |
          *.otf
          *.ttf
          *.woff2

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Sieben-7
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*'
